version: "3"

services:
  grakn:
    image: graknlabs/grakn:1.8.3
    ports:
      - "48555:48555"
    volumes:
      - ./data/:/grakn-core-all-linux/server/db/
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data/:/data
